#!/bin/sh
set -e

# notice the / at end in order to load this module
PACKAGE='process-nextick-args'
SEDCMD="s,(require|resolve)\s*[(]\s*'[.]/,\\1('$PACKAGE/,g"

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT INT TERM HUP

cp -r test* $tmpdir/test*
echo test.js | \
    xargs  -n1  \
	  sh -c 'set -e; echo "TESTING: $3"; sed -E "$1" < "$3" > "$2/$3"' sedtape "$SEDCMD" "$tmpdir"
cd $tmpdir

tap -R spec test.js
